---
abstract: 'Autobox methods to transform Arrays'
author:
  - 'Johan Lindstrom <johanl@cpan.org>'
build_requires:
  Moo: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
  autobox::Core: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: autobox-Array-Transform
requires:
  Carp: 0
  autobox: 0
  parent: 0
  strict: 0
  true: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jplindstrom/p5-autobox-Array-Transform/issues
version: 1.002
